include:
  - local: 'allure-template.yml'

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH != "gh-pages"'
    - changes:
        - '**/allure-history.yml'
      when: never

cache:
  policy: pull-push
  paths:
    - .m2/repository
    - .gradle/caches

stages:
  - build
  - test
  - history
  - allure
  - deploy

build:
  stage: build
  image: gradle:alpine
  script: ./gradlew compileTestJava
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  image: gradle:alpine
  script: ./gradlew test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    when: always
    paths:
      - build/allure-results
    expire_in: 1 day