name: 'Allure Report with history'
description: 'Generate Allure Report with history'
inputs:
  allure_results:
    description: 'Allure test result data dir'
    required: true
    default: 'allure-results'
  allure_report:
    description: 'Allure report target dir'
    required: true
    default: 'allure-report'
  branch:
    description: 'Branch of GitHub Pages'
    required: true
    default: 'gh-pages'
runs:
  using: composite
  steps:
    - name: Step 1
      run: echo 'Composite action'
      shell: bash
    - name: Step2
      run: echo 'Composite action 2'
      shell: bash
    - id: test_1
      name: : test_1
      run: ''
      shell: ''
      uses: actions/checkout@v2

#    - name: Get Allure history
#      uses: actions/checkout@v2
#      if: always()
#      continue-on-error: true
#      with:
#        ref: ${{ inputs.branch }}
#        path: gh-pages
#
#    - name: Allure Report action from marketplace
#      uses: simple-elf/allure-report-action@v1.1
#      if: always()
#      #id: allure-report
#      with:
#        allure_results: ${{ inputs.allure-results }}
#        allure_report: allure-report
#
#    - name: Deploy report to Github Pages
#      if: always()
#      uses: peaceiris/actions-gh-pages@v2
#      env:
#        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#        PUBLISH_BRANCH: ${{ inputs.branch }}
#        PUBLISH_DIR: allure-report


#        - name: Composite Allure Action
#          uses: ./allure-history-action
#          if: always()
#          with:
#            allure_results: build/allure-results
#            #allure_report: allure-report
#            branch: gh-pages